"use strict";

console.log("False == 0: ", false == 0);
console.log("False === 0: ", false === 0);
console.log("False == '': ", false == "");
console.log("False === '': ", false === "");
console.log("0 == '': ", false == 0);
console.log("0 === '': ", false === 0);
console.log("Text == true: ", "Text" == true);
console.log("Text === true: ", "Text" === true);
console.log("undefined == null: ", undefined == null);
console.log("undefined === null: ", undefined === null);
console.log("undefined == false: ", undefined == false);
console.log("null == false: ", null == false);
console.log("undefined == undefined: ", undefined == undefined);
console.log("undefined === undefined: ", undefined === undefined);
console.log("null == null: ", null == null);
console.log("null === null: ", null === null);
console.log("NaN == NaN: ", NaN == NaN);
console.log("NaN === NaN: ", NaN === NaN);
